apiVersion: networking.aci.crossplane.io/v1alpha1
kind: Vrf
metadata:
  name: k8s-vrf-name
  annotations:
    crossplane.io/external-name: test
spec:
  managementPolicies: ["Observe"]
  forProvider:
    name: test
    tenant: crossplane
    nameAlias: the_vrf
  providerConfigRef:
    name: example
