apiVersion: networking.aci.crossplane.io/v1alpha1
kind: Vrf
metadata:
  name: example
spec:
  forProvider:
    name: crossplane-vrf
    tenant: crossplane
    nameAlias: Crosplane
  providerConfigRef:
    name: example
